name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push a branch
      pages: write # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install latest mdbook
        run: |
          mkdir installed-bins
          tag="v0.4.42"
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          curl -Lf "https://github.com/badboy/mdbook-toc/releases/download/0.14.2/mdbook-toc-0.14.2-x86_64-unknown-linux-gnu.tar.gz" | tar -xz --directory=./installed-bins
          echo `pwd`/mdbook >> $GITHUB_PATH
          echo `pwd`/installed-bins >> $GITHUB_PATH
      - name: Build Book
        run: |
          mdbook build
      - name: Fix project-page absolute links
        run: |
          find book -name "*.html" -type f -print0 \
            | xargs -0 perl -pi -e 's#(href|src)="/post/#$1="/pre-34.5/post/#g'
      - name: Disable Jekyll
        run: |
          touch book/.nojekyll
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "book"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
